/**
 * ----------------------------
 * Java JDBC API basis, coding exercises.
 * Exploring java.sql.DriverManager , java.sql.Connection , java.sql.Statement , java.sql.ResultSet features.
 * ----------------------------
 * 
 * fevvelasquez writes the StatementExecutor own class as a factory of 
 * database connected, ready to use, automated Statement instances. 
 * 
 * So, you can execute any valid SQL statement directly and see the results into a StatementResult instance.
 * 
 * 
 * 
 * Even if MySql is used for the demo, a distinct RDBMS or distinct database can be used.
 */
package me.fevvelasquez.jdbc.api.statement;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Executor of multiple Statement instances within a single database connection.
 * 
 * @version 0# 0.2.0. Demo version.
 * @author fevvelasquez@gmail.com
 */
public class StatementExecutor {
	private static final Logger logger = Logger.getLogger(StatementExecutor.class.getName());
	private final Connection connection;

	private StatementExecutor(String url, String username, String password) throws SQLException {
		// Pre-JDBC 4.0 drivers need: Class.forName("com.mysql.jdbc.Driver");
		this.connection = DriverManager.getConnection(url, username, password);
	}

	/**
	 * Get an Executor instance connected to {@code url}.
	 * 
	 * @param url      A valid jdbc-connection-url
	 *                 "jdbc:provider:host:port:database-name".<br>
	 *                 Examples: <br>
	 *                 "jdbc:mysql://localhost:3306/store"<br>
	 *                 "jdbc:oracle:thin:@localhost:1521:orcl"<br>
	 *                 "jdbc:derby:localhost:1521:productDB"
	 * @param username A valid user name.
	 * @param password A valid user password.
	 */
	public static StatementExecutor getInstance(String url, String username, String password) {
		try {
			return new StatementExecutor(url, username, password);
		} catch (SQLException e) {
			logger.severe(e.getMessage());
		}
		return null;
	}

	/**
	 * Create a Statement instance and execute the given SQL statement.
	 * 
	 * @param sqlStatement A valid SQL statement.<br>
	 *                     Examples: <br>
	 *                     "SELECT * FROM products WHERE product_id IN (1,2,3)" <br>
	 *                     "UPDATE products SET name = 'best product' WHERE
	 *                     product_id = 1"
	 * @return The results generated by the SQL Statement execution.
	 */
	public StatementResult executeStatement(String sqlStatement) {
		Statement statement;
		boolean isQuery;
		ResultSet resultset;
		int rowsAffected;

		try {
			statement = connection.createStatement();
			isQuery = statement.execute(sqlStatement);
			resultset = isQuery ? statement.getResultSet() : null;
			rowsAffected = isQuery ? 0 : statement.getUpdateCount();
			return new StatementResult(statement, isQuery, resultset, rowsAffected);
		} catch (SQLException e) {
			logger.severe(e.getMessage());
		}
		return null;

	}

	/**
	 * Release Connection resources.
	 */
	public void close() {
		try {
			connection.close();
			logger.info("Connection closed.");
		} catch (SQLException e) {
			logger.warning(e.getMessage());
		}
	}

}
